### ISSUE TITLE
Bookmark separators are included in duplicates

### ISSUE THREAD

**Issue by floriensk** [zaksid/ext-duplicate-bookmarks-finder#37]
### Bug description
The bookmark separators in Firefox are considered as bookmarks by the extension and thus appear in the duplicate results with the URL "`data:`".

### To reproduce
1. Add a few separators for example to the bookmarks toolbar in Firefox by right-clicking on it and selecting _add separator_.
2. Open the add-on and list all duplicate bookmarks.
3. The separators appear as bookmarks with the URL "`data:`".

### Expected behaviour
As a default behaviour I'd expect separators not to appear.
It might be useful in some cases to be able to list them, though. Such a case might be if one or more bookmarks get deleted (e.g. through this add-on) and as a result of this, the separators between which the bookmarks were end up being stacked up next to each other, which might be undesired. An add-on setting could be introduced to control whether separators (or even, stacked-up separators) may be listed in the duplicate results.

Even if you end up deciding that you let separators appear in the results, it could be useful to indicate that the particular result is about separators. It took me a bit of time to realise what the `data:` URL-s mean.

_Extension version: 0.2_

**Comment by floriensk** [comment]
By the way, the add-on really works great!

**Comment by floriensk** [comment]
That was quick, thanks very much!

**Comment by zaksid** [comment]
@floriensk thanks to you for finding this bug!
